<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "toc"
 *
 * Auto generated by Extension Builder 2016-07-27
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Table of Contents',
	'description' => 'Enables a Table of Contents (TOC) know from Websites like Wikipedia as a plugin for each page which has headlines.',
	'category' => 'plugin',
	'author' => 'Ulf Mayer',
	'author_email' => 'typo3@ulf.info',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'constraints' => array(
		'depends' => array(
			'typo3' => '11.4.0-11.5.99',
			'extbase' => ''		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);
